[theme]
base = "dark"
primaryColor = "#4f98a3"
backgroundColor = "#171614"
secondaryBackgroundColor = "#1c1b19"
textColor = "#e1dfdb"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
